// Generated by Phaser Editor v1.2.1

/**
 * Scene2.
 * @param {Phaser.Game} aGame The game.
 * @param {Phaser.Group} aParent The parent group. If not given the game world will be used instead.
 */
function Scene2(aGame, aParent) {
	Phaser.Group.call(this, aGame, aParent);

	/* --- pre-init-begin --- */

	// you can insert code here

	/* --- pre-init-end --- */

	var prefabRoot_Scene1 = this.game.add.group(this);

	var prefabRoot_Scene1 = this.game.add.group(prefabRoot_Scene1);

	var CollisionLayer = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var CST000C = this.game.add.sprite(4928, 768, 'tiles', 'physics', CollisionLayer);
	CST000C.scale.setTo(2.56, 2.56);

	var CST000B = this.game.add.sprite(4864, 704, 'tiles', 'physics', CollisionLayer);
	CST000B.scale.setTo(2.56, 5.12);

	var CST000A = this.game.add.sprite(4800, 640, 'tiles', 'physics', CollisionLayer);
	CST000A.scale.setTo(2.56, 7.68);

	var CST000 = this.game.add.sprite(4608, 576, 'tiles', 'physics', CollisionLayer);
	CST000.scale.setTo(7.68, 10.24);

	var CPL000A = this.game.add.sprite(1280, 192, 'tiles', 'physics', CollisionLayer);
	CPL000A.scale.setTo(2.56, 25.6);

	var CPL000 = this.game.add.sprite(0, 128, 'tiles', 'physics', CollisionLayer);
	CPL000.scale.setTo(58.88, 2.56);

	var CGR004 = this.game.add.sprite(5056, 704, 'tiles', 'physics', CollisionLayer);
	CGR004.scale.setTo(43.52, 5.12);

	var CGR003 = this.game.add.sprite(4416, 704, 'tiles', 'physics', CollisionLayer);
	CGR003.scale.setTo(7.68, 5.12);

	var CGR002B = this.game.add.sprite(4096, 640, 'tiles', 'physics', CollisionLayer);
	CGR002B.scale.setTo(12.8, 7.68);

	var CGR002A = this.game.add.sprite(3712, 640, 'tiles', 'physics', CollisionLayer);
	CGR002A.scale.setTo(15.36, 2.56);
	CGR002A.body.friction.x = 0.0;

	var CGR002 = this.game.add.sprite(3456, 640, 'tiles', 'physics', CollisionLayer);
	CGR002.scale.setTo(10.24, 7.68);

	var CGR001 = this.game.add.sprite(2880, 768, 'tiles', 'physics', CollisionLayer);
	CGR001.scale.setTo(23.04, 2.56);

	var CGR000 = this.game.add.sprite(1344, 768, 'tiles', 'physics', CollisionLayer);
	CGR000.scale.setTo(51.2, 2.56);

	var Hazards = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var FIREWALL = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var firetilespritesheet13141 = this.game.add.sprite(10112, -128, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet13141.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13151 = this.game.add.sprite(10176, -128, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet13151.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13142 = this.game.add.sprite(10112, -192, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet13142.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13152 = this.game.add.sprite(10176, -192, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet13152.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13143 = this.game.add.sprite(10112, -256, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet13143.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13153 = this.game.add.sprite(10176, -256, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet13153.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13144 = this.game.add.sprite(10112, -320, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet13144.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet13154 = this.game.add.sprite(10176, -320, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet13154.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131411 = this.game.add.sprite(10112, -384, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131411.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131511 = this.game.add.sprite(10176, -384, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131511.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131421 = this.game.add.sprite(10112, -448, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131421.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131521 = this.game.add.sprite(10176, -448, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131521.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131431 = this.game.add.sprite(10112, -512, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131431.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131531 = this.game.add.sprite(10176, -512, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131531.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131441 = this.game.add.sprite(10112, -576, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131441.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131541 = this.game.add.sprite(10176, -576, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131541.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131412 = this.game.add.sprite(10112, -704, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131412.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131512 = this.game.add.sprite(10176, -704, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131512.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131422 = this.game.add.sprite(10112, -768, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131422.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131522 = this.game.add.sprite(10176, -768, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131522.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131432 = this.game.add.sprite(10112, -832, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131432.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131532 = this.game.add.sprite(10176, -832, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131532.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131442 = this.game.add.sprite(10112, -896, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131442.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet131542 = this.game.add.sprite(10176, -896, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet131542.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet1314121 = this.game.add.sprite(10112, -640, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet1314121.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var firetilespritesheet1315121 = this.game.add.sprite(10176, -640, 'firetilespritesheet', 0, FIREWALL);
	firetilespritesheet1315121.animations.add('Flame', [0, 1, 2, 3], 30, true);

	var H010 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);
	H010.position.setTo(67008, 5376);

	var H00F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H00E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);
	H00E.position.setTo(0, 512);

	var H00D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);
	H00D.position.setTo(89344, 7168);

	var H00C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H00B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	var H005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	this.game.add.tileSprite(5248, 640, 64, 64, 'icespikepng', null, H005);

	this.game.add.tileSprite(5376, 640, 64, 64, 'icespikepng', null, H005);

	this.game.add.tileSprite(5504, 640, 64, 64, 'icespikepng', null, H005);

	this.game.add.tileSprite(5632, 640, 64, 64, 'icespikepng', null, H005);

	this.game.add.tileSprite(5760, 640, 64, 64, 'icespikepng', null, H005);

	this.game.add.tileSprite(5888, 640, 64, 64, 'icespikepng', null, H005);

	var H004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	this.game.add.tileSprite(4800, 576, 64, 64, 'singleicespike', null, H004);

	this.game.add.tileSprite(4864, 640, 64, 64, 'singleicespike', null, H004);

	this.game.add.tileSprite(4992, 768, 64, 64, 'singleicespike', null, H004);

	this.game.add.tileSprite(4928, 704, 64, 64, 'singleicespike', null, H004);

	var H003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	this.game.add.tileSprite(4416, 640, 64, 64, 'singleicespike', null, H003);

	this.game.add.tileSprite(4480, 640, 64, 64, 'singleicespike', null, H003);

	this.game.add.tileSprite(4544, 640, 64, 64, 'singleicespike', null, H003);

	var H002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	this.game.add.tileSprite(4096, 576, 64, 64, 'firetilespritesheet', 0, H002);

	this.game.add.tileSprite(4160, 576, 64, 64, 'firetilespritesheet', 0, H002);

	var H001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	this.game.add.tileSprite(3200, 704, 64, 64, 'icespikepng', null, H001);

	this.game.add.tileSprite(3264, 704, 64, 64, 'icespikepng', null, H001);

	this.game.add.tileSprite(3328, 704, 64, 64, 'icespikepng', null, H001);

	this.game.add.tileSprite(3392, 704, 64, 64, 'icespikepng', null, H001);

	var H000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Hazards);

	this.game.add.tileSprite(1856, 704, 64, 64, 'spikepng', null, H000);

	this.game.add.tileSprite(1920, 704, 64, 64, 'spikepng', null, H000);

	var GroundBase = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var Ground4 = this.game.add.tileSprite(2048, -128, 64, 64, 'Ground', 4, GroundBase);
	Ground4.body.immovable = true;
	Ground4.body.allowRotation = false;
	Ground4.body.allowGravity = false;

	this.game.add.tileSprite(3456, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3520, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3584, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3648, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3712, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3776, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3776, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3840, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3520, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3584, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3648, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3712, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3776, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3776, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3840, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3904, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3904, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3968, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3968, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4032, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4096, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4032, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4096, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4160, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4160, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4224, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4224, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4288, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4352, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4288, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4608, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4480, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4352, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4416, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4544, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(3456, 704, 64, 64, 'snowwithgreytilesheet', 3, GroundBase);

	this.game.add.tileSprite(5056, 768, 64, 64, 'snowwithgreytilesheet', 3, GroundBase);

	this.game.add.tileSprite(4608, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4672, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4736, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4800, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4864, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4800, 640, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5184, 1152, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5248, 1152, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5120, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5184, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5248, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5312, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5376, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5440, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5632, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5504, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5568, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5696, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4672, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4736, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4800, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4928, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5504, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5568, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5568, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5632, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5696, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5760, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5824, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5888, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5952, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6016, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6080, 1024, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7552, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7424, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7488, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7104, 640, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4672, 640, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4736, 640, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4864, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5760, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5824, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5888, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5888, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(5952, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6016, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6720, 640, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6784, 640, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6848, 640, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6912, 640, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6976, 640, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7488, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7040, 640, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7424, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7552, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(4608, 640, 64, 64, 'icewithgreytilesheet', 3, GroundBase);

	this.game.add.tileSprite(5312, 1024, 64, 64, 'icewithgreytilesheet', 3, GroundBase);

	this.game.add.tileSprite(6080, 768, 64, 64, 'snowwithgreytilesheet', 5, GroundBase);

	this.game.add.tileSprite(6400, 704, 64, 64, 'snowwithgreytilesheet', 3, GroundBase);

	this.game.add.tileSprite(6464, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6528, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6592, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6656, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6720, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6784, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6976, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6848, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6912, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7040, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7104, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7168, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7232, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7232, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7296, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7360, 704, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7616, 1024, 64, 64, 'snowwithgreytilesheet', 5, GroundBase);

	this.game.add.tileSprite(6400, 768, 64, 64, 'snowwithgreytilesheet', 3, GroundBase);

	this.game.add.tileSprite(6464, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6528, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6592, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6656, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6720, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6784, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6976, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6848, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(6912, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7040, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7104, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7168, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7232, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7232, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7296, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7360, 768, 64, 64, 'snowwithgreytilesheet', 4, GroundBase);

	this.game.add.tileSprite(7616, 1088, 64, 64, 'snowwithgreytilesheet', 5, GroundBase);

	var Arrows = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var arrow = this.game.add.sprite(0, 896, 'arrow', null, Arrows);

	var player = this.game.add.sprite(0, 0, 'urlsheetfixed', 0, prefabRoot_Scene1);
	player.animations.add('swordWalk', [1, 2, 3, 2], 30, false);
	player.animations.add('swordIdle', [0], 60, false);
	player.animations.add('bowIdle', [6], 60, false);
	player.animations.add('bowWalk', [7, 8, 9, 10], 30, false);
	player.animations.add('swordAttack', [4, 5, 4], 30, false);
	this.game.physics.arcade.enable(player);
	player.body.setSize(45.0, 100.0, 17.0, 0.0);

	var Romans = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var roman = this.game.add.sprite(704, 0, 'roman', 0, Romans);
	roman.animations.add('walk', [1, 2, 3, 2], 4, true);
	roman.animations.add('idle', [0], 4, false);
	roman.body.setSize(45.0, 100.0, 17.0, 0.0);

	var roman1 = this.game.add.sprite(1216, 0, 'roman', 0, Romans);
	roman1.animations.add('walk', [1, 2, 3, 2], 4, true);
	roman1.animations.add('idle', [0], 4, false);
	roman1.body.setSize(45.0, 100.0, 17.0, 0.0);

	var roman2 = this.game.add.sprite(1408, 640, 'roman', 0, Romans);
	roman2.animations.add('walk', [1, 2, 3, 2], 4, true);
	roman2.animations.add('idle', [0], 4, false);
	roman2.body.setSize(45.0, 100.0, 17.0, 0.0);

	var roman3 = this.game.add.sprite(2048, 640, 'roman', 0, Romans);
	roman3.animations.add('walk', [1, 2, 3, 2], 4, true);
	roman3.animations.add('idle', [0], 4, false);
	roman3.body.setSize(45.0, 100.0, 17.0, 0.0);

	var Water = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var W006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	var W005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	var W004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	var W003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	var W002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	this.game.add.tileSprite(6144, 768, 64, 64, 'watersprite1', null, W002);

	this.game.add.tileSprite(6208, 768, 64, 64, 'watersprite1', null, W002);

	this.game.add.tileSprite(6272, 768, 64, 64, 'watersprite1', null, W002);

	this.game.add.tileSprite(6336, 768, 64, 64, 'watersprite1', null, W002);

	var W001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	this.game.add.tileSprite(2624, 768, 64, 64, 'watersprite1', null, W001);

	this.game.add.tileSprite(2688, 768, 64, 64, 'watersprite1', null, W001);

	this.game.add.tileSprite(2752, 768, 64, 64, 'watersprite1', null, W001);

	this.game.add.tileSprite(2816, 768, 64, 64, 'watersprite1', null, W001);

	var W000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Water);

	this.game.add.tileSprite(64, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(128, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(128, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(192, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(192, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(384, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(384, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(448, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(448, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(64, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(512, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(512, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(704, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(704, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(768, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(768, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(832, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(832, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(1024, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(1024, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(1088, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(1088, 768, 64, 64, 'watersprite1', null, W000);

	this.game.add.tileSprite(1152, 704, 64, 64, 'watersprite2', null, W000);

	this.game.add.tileSprite(1152, 768, 64, 64, 'watersprite1', null, W000);

	var Plat = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var ST004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	ST004.position.setTo(67008, 5376);

	var ST003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var ST002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var ST001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var ST000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(4608, 576, 64, 64, 'icewithgreytilesheet', 0, ST000);

	this.game.add.tileSprite(4672, 576, 64, 64, 'icewithgreytilesheet', 1, ST000);

	this.game.add.tileSprite(4736, 576, 64, 64, 'icewithgreytilesheet', 2, ST000);

	this.game.add.tileSprite(5376, 1088, 64, 64, 'icewithgreytilesheet', 2, ST000);

	this.game.add.tileSprite(5440, 1152, 64, 64, 'icewithgreytilesheet', 2, ST000);

	this.game.add.tileSprite(5504, 1216, 64, 64, 'icewithgreytilesheet', 2, ST000);

	this.game.add.tileSprite(5568, 1088, 64, 64, 'icewithgreytilesheet', 5, ST000);

	this.game.add.tileSprite(5632, 1152, 64, 64, 'icewithgreytilesheet', 5, ST000);

	this.game.add.tileSprite(5696, 1216, 64, 64, 'icewithgreytilesheet', 5, ST000);

	var PL024 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL024.position.setTo(67008, 5376);

	var PL023 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL023.position.setTo(44672, 3584);

	var PL022 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL022.position.setTo(67008, 5376);

	var PL021 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL021.position.setTo(44672, 3584);

	var PL020 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL020.position.setTo(44672, 3584);

	var PL01F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01F.position.setTo(67008, 5376);

	var PL01E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01E.position.setTo(67008, 5376);

	var PL01D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01D.position.setTo(44672, 3584);

	var PL01C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01C.position.setTo(44672, 3584);

	var PL01B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01B.position.setTo(44672, 3584);

	var PL01A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL01A.position.setTo(44672, 3584);

	var PL019 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL019.position.setTo(22336, 1792);

	var PL018 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL018.position.setTo(22336, 1792);

	var PL017 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL017.position.setTo(22336, 1792);

	var PL016 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	PL016.position.setTo(22336, 1792);

	var PL015 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL014 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL013 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL012 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL011 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL010 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var PL000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(1408, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1344, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1152, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 768, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 704, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 640, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 576, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 512, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 448, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 384, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 320, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 256, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1216, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1344, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 768, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 704, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 640, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 576, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 512, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 448, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 384, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 320, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 256, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1280, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(832, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 768, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 704, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 640, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 576, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 512, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 448, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 384, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 320, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 256, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1024, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 768, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 704, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 640, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 576, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 512, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 448, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 384, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 320, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 256, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(512, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 768, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 704, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 640, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 576, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 512, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 448, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 384, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 320, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 256, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(704, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 768, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 704, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 640, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 576, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 512, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 448, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 384, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 320, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 256, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(192, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 768, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 704, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 640, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 576, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 512, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 448, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 384, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 320, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 256, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(384, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 768, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 704, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 640, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 576, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 512, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 448, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 384, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 320, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 256, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(64, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1152, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1088, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(1024, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(960, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(896, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(832, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(768, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(704, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(640, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(576, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(512, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(448, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(384, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(320, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(256, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(192, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(128, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(64, 128, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 768, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 704, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 640, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 576, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 512, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 448, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 384, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 320, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 256, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 192, 64, 64, 'spritesheet', 1, PL000);

	this.game.add.tileSprite(0, 128, 64, 64, 'spritesheet', 1, PL000);

	var OB016 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB015 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB015.position.setTo(44672, 3584);

	var OB014 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB014.position.setTo(67008, 5376);

	var OB013 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB013.position.setTo(44672, 3584);

	var OB012 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB012.position.setTo(22336, 1792);

	var OB011 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB011.position.setTo(22336, 1792);

	var OB010 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB010.position.setTo(44672, 3584);

	var OB00F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB00F.position.setTo(22336, 1792);

	var OB00E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB00E.position.setTo(22336, 1792);

	var OB00D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);
	OB00D.position.setTo(44672, 3584);

	var OB00C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB00B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var OB002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(6720, 576, 64, 64, 'singleblockicegrey', null, OB002);

	this.game.add.tileSprite(7104, 576, 64, 64, 'icewithgrey', 2, OB002);

	this.game.add.tileSprite(7040, 576, 64, 64, 'icewithgrey', 0, OB002);

	var OB001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(5184, 640, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5184, 576, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5312, 640, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5312, 576, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5440, 640, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5440, 576, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5568, 640, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5568, 576, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5696, 640, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5696, 576, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5824, 640, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5824, 576, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5952, 640, 64, 64, 'crate', null, OB001);

	this.game.add.tileSprite(5952, 576, 64, 64, 'crate', null, OB001);

	var OB000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(3072, 704, 64, 64, 'crate', null, OB000);

	this.game.add.tileSprite(3136, 704, 64, 64, 'crate', null, OB000);

	this.game.add.tileSprite(3136, 640, 64, 64, 'crate', null, OB000);

	var GR00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	var GR005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(6400, 640, 64, 64, 'snowwithgreytilesheet', 0, GR005);

	this.game.add.tileSprite(6528, 640, 64, 64, 'snowwithgrey', 1, GR005);

	this.game.add.tileSprite(6464, 640, 64, 64, 'snowwithgrey', 1, GR005);

	this.game.add.tileSprite(7168, 640, 64, 64, 'snowwithgrey', 1, GR005);

	this.game.add.tileSprite(7360, 640, 64, 64, 'snowwithgrey', 1, GR005);

	this.game.add.tileSprite(7296, 640, 64, 64, 'snowwithgrey', 1, GR005);

	this.game.add.tileSprite(7232, 640, 64, 64, 'snowwithgrey', 1, GR005);

	this.game.add.tileSprite(7552, 640, 64, 64, 'snowwithgrey', 1, GR005);

	this.game.add.tileSprite(7488, 640, 64, 64, 'snowwithgrey', 1, GR005);

	this.game.add.tileSprite(7424, 640, 64, 64, 'snowwithgrey', 1, GR005);

	this.game.add.tileSprite(6592, 640, 64, 64, 'icewithgrey', 1, GR005);

	this.game.add.tileSprite(6656, 640, 64, 64, 'icewithgrey', 1, GR005);

	var GR004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(6080, 704, 64, 64, 'snowwithgreytilesheet', 2, GR004);

	this.game.add.tileSprite(5120, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5056, 704, 64, 64, 'snowwithgreytilesheet', 0, GR004);

	this.game.add.tileSprite(5184, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5248, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5312, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5376, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5440, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5504, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5568, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5632, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5696, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5760, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5824, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5888, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(5952, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	this.game.add.tileSprite(6016, 704, 64, 64, 'snowwithgreytilesheet', 1, GR004);

	var GR003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(4416, 704, 64, 64, 'snowwithgrey', 1, GR003);

	this.game.add.tileSprite(4480, 704, 64, 64, 'snowwithgrey', 1, GR003);

	this.game.add.tileSprite(4544, 704, 64, 64, 'snowwithgrey', 1, GR003);

	var GR002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(4352, 640, 64, 64, 'snowwithgrey', 2, GR002);

	this.game.add.tileSprite(3456, 640, 64, 64, 'snowwithgreytilesheet', 0, GR002);

	this.game.add.tileSprite(3520, 640, 64, 64, 'snowwithgrey', 1, GR002);

	this.game.add.tileSprite(3584, 640, 64, 64, 'snowwithgrey', 1, GR002);

	this.game.add.tileSprite(3648, 640, 64, 64, 'snowwithgrey', 1, GR002);

	this.game.add.tileSprite(4096, 640, 64, 64, 'snowwithgrey', 1, GR002);

	this.game.add.tileSprite(4160, 640, 64, 64, 'snowwithgrey', 1, GR002);

	this.game.add.tileSprite(4224, 640, 64, 64, 'snowwithgrey', 1, GR002);

	this.game.add.tileSprite(4288, 640, 64, 64, 'snowwithgrey', 1, GR002);

	this.game.add.tileSprite(3712, 640, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(3776, 640, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(3840, 640, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(3904, 640, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(3968, 640, 64, 64, 'icewithgreytilesheet', 1, GR002);

	this.game.add.tileSprite(4032, 640, 64, 64, 'icewithgreytilesheet', 1, GR002);

	var GR001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(2944, 768, 64, 64, 'snowwithgrey', 1, GR001);

	this.game.add.tileSprite(2880, 768, 64, 64, 'snowwithgrey', 0, GR001);

	this.game.add.tileSprite(3008, 768, 64, 64, 'snowwithgrey', 1, GR001);

	this.game.add.tileSprite(3072, 768, 64, 64, 'snowwithgrey', 1, GR001);

	this.game.add.tileSprite(3136, 768, 64, 64, 'snowwithgrey', 1, GR001);

	this.game.add.tileSprite(3200, 768, 64, 64, 'snowwithgrey', 1, GR001);

	this.game.add.tileSprite(3264, 768, 64, 64, 'snowwithgrey', 1, GR001);

	this.game.add.tileSprite(3328, 768, 64, 64, 'snowwithgrey', 1, GR001);

	this.game.add.tileSprite(3392, 768, 64, 64, 'snowwithgrey', 1, GR001);

	var GR000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, Plat);

	this.game.add.tileSprite(2496, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(2432, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(2368, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(2304, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(2240, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(2176, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(2112, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(2048, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1984, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1920, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1856, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1792, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1728, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1664, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1600, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1536, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1472, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1408, 768, 64, 64, 'Ground', 1, GR000);

	this.game.add.tileSprite(1344, 768, 64, 64, 'Ground', 0, GR000);

	this.game.add.tileSprite(2560, 768, 64, 64, 'Ground', 2, GR000);

	var endScreen = this.game.add.group(prefabRoot_Scene1);

	var startScreen = this.game.add.group(prefabRoot_Scene1);

	var theDress = this.game.add.physicsGroup(Phaser.Physics.ARCADE, prefabRoot_Scene1);

	var MasterGroup = this.game.add.physicsGroup(Phaser.Physics.ARCADE, this);

	this.game.add.tileSprite(7104, 1152, 64, 64, 'urlsnowsprite2', 7, MasterGroup);

	this.game.add.tileSprite(7040, 1152, 64, 64, 'urlsnowsprite2', 6, MasterGroup);

	this.game.add.tileSprite(7168, 1088, 64, 64, 'urlsnowsprite2', 5, MasterGroup);

	this.game.add.tileSprite(7104, 1088, 64, 64, 'urlsnowsprite2', 4, MasterGroup);

	this.game.add.tileSprite(7040, 1088, 64, 64, 'urlsnowsprite2', 3, MasterGroup);

	this.game.add.tileSprite(7168, 1024, 64, 64, 'urlsnowsprite2', 2, MasterGroup);

	this.game.add.tileSprite(7104, 1024, 64, 64, 'urlsnowsprite2', 1, MasterGroup);

	this.game.add.tileSprite(7040, 1024, 64, 64, 'urlsnowsprite2', 0, MasterGroup);

	this.game.add.tileSprite(7168, 1152, 64, 64, 'urlsnowsprite2', 8, MasterGroup);

	this.game.add.tileSprite(7168, 1344, 64, 64, 'urlsnowsprite', 8, MasterGroup);

	this.game.add.tileSprite(7104, 1344, 64, 64, 'urlsnowsprite', 7, MasterGroup);

	this.game.add.tileSprite(7040, 1344, 64, 64, 'urlsnowsprite', 6, MasterGroup);

	this.game.add.tileSprite(7168, 1280, 64, 64, 'urlsnowsprite', 5, MasterGroup);

	this.game.add.tileSprite(7104, 1280, 64, 64, 'urlsnowsprite', 4, MasterGroup);

	this.game.add.tileSprite(7040, 1280, 64, 64, 'urlsnowsprite', 3, MasterGroup);

	this.game.add.tileSprite(7168, 1216, 64, 64, 'urlsnowsprite', 2, MasterGroup);

	this.game.add.tileSprite(7104, 1216, 64, 64, 'urlsnowsprite', 1, MasterGroup);

	this.game.add.tileSprite(7040, 1216, 64, 64, 'urlsnowsprite', 0, MasterGroup);

	this.game.add.tileSprite(7360, 1472, 64, 64, 'firetilespritesheet', 3, MasterGroup);

	this.game.add.tileSprite(7296, 1472, 64, 64, 'firetilespritesheet', 2, MasterGroup);

	this.game.add.tileSprite(7232, 1472, 64, 64, 'firetilespritesheet', 1, MasterGroup);

	this.game.add.tileSprite(7168, 1472, 64, 64, 'firetilespritesheet', 0, MasterGroup);

	this.game.add.tileSprite(7168, 1408, 64, 64, 'spritesheet', 2, MasterGroup);

	this.game.add.tileSprite(7104, 1408, 64, 64, 'spritesheet', 1, MasterGroup);

	this.game.add.tileSprite(7040, 1408, 64, 64, 'spritesheet', 0, MasterGroup);

	this.game.add.tileSprite(1280, 1088, 64, 64, 'Ground', 8, MasterGroup);

	this.game.add.tileSprite(1216, 1088, 64, 64, 'Ground', 7, MasterGroup);

	this.game.add.tileSprite(1152, 1088, 64, 64, 'Ground', 6, MasterGroup);

	this.game.add.tileSprite(1280, 1024, 64, 64, 'Ground', 5, MasterGroup);

	this.game.add.tileSprite(1216, 1024, 64, 64, 'Ground', 4, MasterGroup);

	this.game.add.tileSprite(1152, 1024, 64, 64, 'Ground', 3, MasterGroup);

	this.game.add.tileSprite(1280, 960, 64, 64, 'Ground', 2, MasterGroup);

	this.game.add.tileSprite(1216, 960, 64, 64, 'Ground', 1, MasterGroup);

	this.game.add.tileSprite(1152, 960, 64, 64, 'Ground', 0, MasterGroup);

	this.game.add.tileSprite(6848, 1472, 64, 64, 'spikepng', null, MasterGroup);

	this.game.add.tileSprite(7168, 1536, 64, 64, 'watersprite2', null, MasterGroup);

	this.game.add.tileSprite(7168, 1600, 64, 64, 'watersprite1', null, MasterGroup);

	this.game.add.tileSprite(6912, 1408, 64, 64, 'cavetile', null, MasterGroup);

	this.game.add.tileSprite(7040, 1600, 64, 64, 'crate', null, MasterGroup);

	this.game.add.tileSprite(1408, 1024, 64, 64, 'overhangsinglesprite', null, MasterGroup);

	this.game.add.tileSprite(7232, 1152, 64, 64, 'singlesnow', null, MasterGroup);

	this.game.add.tileSprite(7104, 1600, 64, 64, 'singleicespike', null, MasterGroup);

	this.game.add.tileSprite(7296, 1152, 64, 64, 'singleblocksnow', null, MasterGroup);

	this.game.add.tileSprite(7296, 1344, 64, 64, 'singleblockice', null, MasterGroup);

	this.game.add.tileSprite(1408, 1088, 64, 64, 'oneblocksprite', null, MasterGroup);

	this.game.add.tileSprite(7104, 1536, 64, 64, 'icespikereverse', null, MasterGroup);

	this.game.add.tileSprite(7296, 1280, 64, 64, 'singleblockiceoverhang', null, MasterGroup);

	this.game.add.tileSprite(7296, 1088, 64, 64, 'singleblocksnowoverhang', null, MasterGroup);

	this.game.add.tileSprite(7360, 1024, 64, 64, 'snowoverhang', 2, MasterGroup);

	this.game.add.tileSprite(7296, 1024, 64, 64, 'snowoverhang', 1, MasterGroup);

	this.game.add.tileSprite(7232, 1024, 64, 64, 'snowoverhang', 0, MasterGroup);

	this.game.add.tileSprite(7360, 1216, 64, 64, 'iceoverhang', 2, MasterGroup);

	this.game.add.tileSprite(7296, 1216, 64, 64, 'iceoverhang', 1, MasterGroup);

	this.game.add.tileSprite(7232, 1216, 64, 64, 'iceoverhang', 0, MasterGroup);

	this.game.add.tileSprite(1472, 960, 64, 64, 'overhangsprite', 2, MasterGroup);

	this.game.add.tileSprite(1408, 960, 64, 64, 'overhangsprite', 1, MasterGroup);

	this.game.add.tileSprite(1344, 960, 64, 64, 'overhangsprite', 0, MasterGroup);

	this.game.add.tileSprite(6784, 1024, 64, 64, 'snowwithgrey', 2, MasterGroup);

	this.game.add.tileSprite(6720, 1024, 64, 64, 'snowwithgrey', 1, MasterGroup);

	this.game.add.tileSprite(6656, 1024, 64, 64, 'snowwithgrey', 0, MasterGroup);

	this.game.add.tileSprite(6784, 1216, 64, 64, 'icewithgrey', 2, MasterGroup);

	this.game.add.tileSprite(6720, 1216, 64, 64, 'icewithgrey', 1, MasterGroup);

	this.game.add.tileSprite(6656, 1216, 64, 64, 'icewithgrey', 0, MasterGroup);

	this.game.add.tileSprite(6976, 1344, 64, 64, 'icewithgreytilesheet', 8, MasterGroup);

	this.game.add.tileSprite(6912, 1344, 64, 64, 'icewithgreytilesheet', 7, MasterGroup);

	this.game.add.tileSprite(6848, 1344, 64, 64, 'icewithgreytilesheet', 6, MasterGroup);

	this.game.add.tileSprite(6976, 1280, 64, 64, 'icewithgreytilesheet', 5, MasterGroup);

	this.game.add.tileSprite(6912, 1280, 64, 64, 'icewithgreytilesheet', 4, MasterGroup);

	this.game.add.tileSprite(6848, 1280, 64, 64, 'icewithgreytilesheet', 3, MasterGroup);

	this.game.add.tileSprite(6976, 1216, 64, 64, 'icewithgreytilesheet', 2, MasterGroup);

	this.game.add.tileSprite(6912, 1216, 64, 64, 'icewithgreytilesheet', 1, MasterGroup);

	this.game.add.tileSprite(6848, 1216, 64, 64, 'icewithgreytilesheet', 0, MasterGroup);

	this.game.add.tileSprite(6976, 1152, 64, 64, 'snowwithgreytilesheet', 8, MasterGroup);

	this.game.add.tileSprite(6912, 1152, 64, 64, 'snowwithgreytilesheet', 7, MasterGroup);

	this.game.add.tileSprite(6848, 1152, 64, 64, 'snowwithgreytilesheet', 6, MasterGroup);

	this.game.add.tileSprite(6976, 1088, 64, 64, 'snowwithgreytilesheet', 5, MasterGroup);

	this.game.add.tileSprite(6912, 1088, 64, 64, 'snowwithgreytilesheet', 4, MasterGroup);

	this.game.add.tileSprite(6848, 1088, 64, 64, 'snowwithgreytilesheet', 3, MasterGroup);

	this.game.add.tileSprite(6976, 1024, 64, 64, 'snowwithgreytilesheet', 2, MasterGroup);

	this.game.add.tileSprite(6912, 1024, 64, 64, 'snowwithgreytilesheet', 1, MasterGroup);

	this.game.add.tileSprite(6848, 1024, 64, 64, 'snowwithgreytilesheet', 0, MasterGroup);

	this.game.add.tileSprite(6976, 1472, 64, 64, 'icespikepngright', null, MasterGroup);

	this.game.add.tileSprite(6912, 1536, 64, 64, 'icespikepngleft', null, MasterGroup);

	this.game.add.tileSprite(6976, 1536, 64, 64, 'icespikepngdown', null, MasterGroup);

	this.game.add.tileSprite(6720, 1088, 64, 64, 'singleblocksnowgrey', null, MasterGroup);

	this.game.add.tileSprite(6720, 1280, 64, 64, 'singleblockicegrey', null, MasterGroup);

	this.game.add.tileSprite(6912, 1472, 64, 64, 'icespikepng', null, MasterGroup);

	 // public fields

	this.fCollisionLayer = CollisionLayer;
	this.fHazards = Hazards;
	this.fFIREWALL = FIREWALL;
	this.fH010 = H010;
	this.fH00F = H00F;
	this.fH00E = H00E;
	this.fH00D = H00D;
	this.fH00C = H00C;
	this.fH00B = H00B;
	this.fH00A = H00A;
	this.fH009 = H009;
	this.fH008 = H008;
	this.fH007 = H007;
	this.fH006 = H006;
	this.fH005 = H005;
	this.fH004 = H004;
	this.fH003 = H003;
	this.fH002 = H002;
	this.fH001 = H001;
	this.fH000 = H000;
	this.fGroundBase = GroundBase;
	this.fArrows = Arrows;
	this.fArrow = arrow;
	this.fPlayer = player;
	this.fRomans = Romans;
	this.fRoman = roman;
	this.fRoman1 = roman1;
	this.fRoman2 = roman2;
	this.fRoman3 = roman3;
	this.fWater = Water;
	this.fW006 = W006;
	this.fW005 = W005;
	this.fW004 = W004;
	this.fW003 = W003;
	this.fW002 = W002;
	this.fW001 = W001;
	this.fW000 = W000;
	this.fPlat = Plat;
	this.fST004 = ST004;
	this.fST003 = ST003;
	this.fST002 = ST002;
	this.fST001 = ST001;
	this.fST000 = ST000;
	this.fPL024 = PL024;
	this.fPL023 = PL023;
	this.fPL022 = PL022;
	this.fPL021 = PL021;
	this.fPL020 = PL020;
	this.fPL01F = PL01F;
	this.fPL01E = PL01E;
	this.fPL01D = PL01D;
	this.fPL01C = PL01C;
	this.fPL01B = PL01B;
	this.fPL01A = PL01A;
	this.fPL019 = PL019;
	this.fPL018 = PL018;
	this.fPL017 = PL017;
	this.fPL016 = PL016;
	this.fPL015 = PL015;
	this.fPL014 = PL014;
	this.fPL013 = PL013;
	this.fPL012 = PL012;
	this.fPL011 = PL011;
	this.fPL010 = PL010;
	this.fPL00F = PL00F;
	this.fPL00E = PL00E;
	this.fPL00D = PL00D;
	this.fPL00C = PL00C;
	this.fPL00B = PL00B;
	this.fPL00A = PL00A;
	this.fPL009 = PL009;
	this.fPL008 = PL008;
	this.fPL007 = PL007;
	this.fPL006 = PL006;
	this.fPL005 = PL005;
	this.fPL004 = PL004;
	this.fPL003 = PL003;
	this.fPL002 = PL002;
	this.fPL001 = PL001;
	this.fPL000 = PL000;
	this.fOB016 = OB016;
	this.fOB015 = OB015;
	this.fOB014 = OB014;
	this.fOB013 = OB013;
	this.fOB012 = OB012;
	this.fOB011 = OB011;
	this.fOB010 = OB010;
	this.fOB00F = OB00F;
	this.fOB00E = OB00E;
	this.fOB00D = OB00D;
	this.fOB00C = OB00C;
	this.fOB00B = OB00B;
	this.fOB00A = OB00A;
	this.fOB009 = OB009;
	this.fOB008 = OB008;
	this.fOB007 = OB007;
	this.fOB006 = OB006;
	this.fOB005 = OB005;
	this.fOB004 = OB004;
	this.fOB003 = OB003;
	this.fOB002 = OB002;
	this.fOB001 = OB001;
	this.fOB000 = OB000;
	this.fGR00A = GR00A;
	this.fGR009 = GR009;
	this.fGR008 = GR008;
	this.fGR007 = GR007;
	this.fGR006 = GR006;
	this.fGR005 = GR005;
	this.fGR004 = GR004;
	this.fGR003 = GR003;
	this.fGR002 = GR002;
	this.fGR001 = GR001;
	this.fGR000 = GR000;
	this.fEndScreen = endScreen;
	this.fStartScreen = startScreen;
	this.fTheDress = theDress;
	this.fMasterGroup = MasterGroup;

	/* --- post-init-begin --- */

	// you can insert code here

	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var Scene2_proto = Object.create(Phaser.Group.prototype);
Scene2.prototype = Scene2_proto;
Scene2.prototype.constructor = Phaser.Group;

/* --- end generated code --- */
// -- user code here --
