
// -- user code here --

/* --- start generated code --- */

// Generated by Phaser Editor v1.4.1 (Phaser v2.6.2)


/**
 * Scene3.
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Phaser.Group} aParent The parent Group (or other {@link DisplayObject}) that this group will be added to.    If undefined/unspecified the Group will be added to the {@link Phaser.Game#world Game World}; if null the Group will not be added to any parent.
 * @param {string} aName A name for this group. Not used internally but useful for debugging.
 * @param {boolean} aAddToStage If true this group will be added directly to the Game.Stage instead of Game.World.
 * @param {boolean} aEnableBody If true all Sprites created with {@link #create} or {@link #createMulitple} will have a physics body created on them. Change the body type with {@link #physicsBodyType}.
 * @param {number} aPhysicsBodyType The physics body type to use when physics bodies are automatically added. See {@link #physicsBodyType} for values.
 */
function Scene3(aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType) {
	
	Phaser.Group.call(this, aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType);
	var _prefabRoot_Scene1 = this.game.add.group(this);
	
	var _CollisionLayer = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _prefabRoot_Scene1);
	
	var _CGR000 = this.game.add.sprite(0, 704, 'tiles', 'physics', _CollisionLayer);
	_CGR000.scale.setTo(69.12, 2.56);
	
	var _Water = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _prefabRoot_Scene1);
	
	var _W006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Water);
	
	var _W005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Water);
	
	var _W004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Water);
	
	var _W003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Water);
	
	var _W002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Water);
	
	var _W001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Water);
	
	var _Hazards = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _prefabRoot_Scene1);
	
	var _FIREWALL = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H010 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	_H010.position.setTo(67008, 5376);
	
	var _H00F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H00E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	_H00E.position.setTo(0, 512);
	
	var _H00D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	_H00D.position.setTo(89344, 7168);
	
	var _H00C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H00B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _H000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Hazards);
	
	var _GroundBase = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _prefabRoot_Scene1);
	
	var _Ground4 = this.game.add.tileSprite(0, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground4.body.immovable = true;
	_Ground4.body.allowRotation = false;
	_Ground4.body.allowGravity = false;
	
	var _Ground41 = this.game.add.tileSprite(64, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground41.body.immovable = true;
	_Ground41.body.allowRotation = false;
	_Ground41.body.allowGravity = false;
	
	var _Ground42 = this.game.add.tileSprite(128, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground42.body.immovable = true;
	_Ground42.body.allowRotation = false;
	_Ground42.body.allowGravity = false;
	
	var _Ground43 = this.game.add.tileSprite(192, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground43.body.immovable = true;
	_Ground43.body.allowRotation = false;
	_Ground43.body.allowGravity = false;
	
	var _Ground44 = this.game.add.tileSprite(256, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground44.body.immovable = true;
	_Ground44.body.allowRotation = false;
	_Ground44.body.allowGravity = false;
	
	var _Ground45 = this.game.add.tileSprite(320, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground45.body.immovable = true;
	_Ground45.body.allowRotation = false;
	_Ground45.body.allowGravity = false;
	
	var _Ground46 = this.game.add.tileSprite(384, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground46.body.immovable = true;
	_Ground46.body.allowRotation = false;
	_Ground46.body.allowGravity = false;
	
	var _Ground47 = this.game.add.tileSprite(448, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground47.body.immovable = true;
	_Ground47.body.allowRotation = false;
	_Ground47.body.allowGravity = false;
	
	var _Ground48 = this.game.add.tileSprite(512, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground48.body.immovable = true;
	_Ground48.body.allowRotation = false;
	_Ground48.body.allowGravity = false;
	
	var _Ground49 = this.game.add.tileSprite(576, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground49.body.immovable = true;
	_Ground49.body.allowRotation = false;
	_Ground49.body.allowGravity = false;
	
	var _Ground410 = this.game.add.tileSprite(640, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground410.body.immovable = true;
	_Ground410.body.allowRotation = false;
	_Ground410.body.allowGravity = false;
	
	var _Ground411 = this.game.add.tileSprite(704, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground411.body.immovable = true;
	_Ground411.body.allowRotation = false;
	_Ground411.body.allowGravity = false;
	
	var _Ground412 = this.game.add.tileSprite(768, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground412.body.immovable = true;
	_Ground412.body.allowRotation = false;
	_Ground412.body.allowGravity = false;
	
	var _Ground413 = this.game.add.tileSprite(832, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground413.body.immovable = true;
	_Ground413.body.allowRotation = false;
	_Ground413.body.allowGravity = false;
	
	var _Ground414 = this.game.add.tileSprite(896, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground414.body.immovable = true;
	_Ground414.body.allowRotation = false;
	_Ground414.body.allowGravity = false;
	
	var _Ground415 = this.game.add.tileSprite(960, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground415.body.immovable = true;
	_Ground415.body.allowRotation = false;
	_Ground415.body.allowGravity = false;
	
	var _Ground416 = this.game.add.tileSprite(1024, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground416.body.immovable = true;
	_Ground416.body.allowRotation = false;
	_Ground416.body.allowGravity = false;
	
	var _Ground417 = this.game.add.tileSprite(1088, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground417.body.immovable = true;
	_Ground417.body.allowRotation = false;
	_Ground417.body.allowGravity = false;
	
	var _Ground418 = this.game.add.tileSprite(1152, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground418.body.immovable = true;
	_Ground418.body.allowRotation = false;
	_Ground418.body.allowGravity = false;
	
	var _Ground419 = this.game.add.tileSprite(1216, 768, 64, 64, 'Ground', 4, _GroundBase);
	_Ground419.body.immovable = true;
	_Ground419.body.allowRotation = false;
	_Ground419.body.allowGravity = false;
	
	var _Arrows = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _prefabRoot_Scene1);
	
	var _arrow = this.game.add.sprite(0, 896, 'arrow', null, _Arrows);
	
	var _player = this.game.add.sprite(128, 576, 'urlsheetfixed', 0, _prefabRoot_Scene1);
	_player.animations.add('swordWalk', [1, 2, 3, 2], 30, false);
	_player.animations.add('swordIdle', [0], 60, false);
	_player.animations.add('bowIdle', [6], 60, false);
	_player.animations.add('bowWalk', [7, 8, 9, 10], 30, false);
	_player.animations.add('swordAttack', [4, 5, 4], 30, false);
	this.game.physics.arcade.enable(_player);
	_player.body.setSize(45.0, 100.0, 17.0, 0.0);
	
	var _Romans = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _prefabRoot_Scene1);
	
	var _Plat = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _prefabRoot_Scene1);
	
	var _ST004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_ST004.position.setTo(67008, 5376);
	
	var _ST003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _ST002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _ST001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _ST000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL024 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL024.position.setTo(67008, 5376);
	
	var _PL023 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL023.position.setTo(44672, 3584);
	
	var _PL022 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL022.position.setTo(67008, 5376);
	
	var _PL021 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL021.position.setTo(44672, 3584);
	
	var _PL020 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL020.position.setTo(44672, 3584);
	
	var _PL01F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL01F.position.setTo(67008, 5376);
	
	var _PL01E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL01E.position.setTo(67008, 5376);
	
	var _PL01D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL01D.position.setTo(44672, 3584);
	
	var _PL01C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL01C.position.setTo(44672, 3584);
	
	var _PL01B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL01B.position.setTo(44672, 3584);
	
	var _PL01A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL01A.position.setTo(44672, 3584);
	
	var _PL019 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL019.position.setTo(22336, 1792);
	
	var _PL018 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL018.position.setTo(22336, 1792);
	
	var _PL017 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL017.position.setTo(22336, 1792);
	
	var _PL016 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_PL016.position.setTo(22336, 1792);
	
	var _PL015 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL014 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL013 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL012 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL011 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL010 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL00F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL00E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL00D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL00C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL00B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _PL000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB016 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB015 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_OB015.position.setTo(44672, 3584);
	
	var _OB014 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_OB014.position.setTo(67008, 5376);
	
	var _OB013 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_OB013.position.setTo(44672, 3584);
	
	var _OB012 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_OB012.position.setTo(22336, 1792);
	
	var _OB011 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_OB011.position.setTo(22336, 1792);
	
	var _OB010 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_OB010.position.setTo(44672, 3584);
	
	var _OB00F = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_OB00F.position.setTo(22336, 1792);
	
	var _OB00E = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_OB00E.position.setTo(22336, 1792);
	
	var _OB00D = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	_OB00D.position.setTo(44672, 3584);
	
	var _OB00C = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB00B = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _OB000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR00A = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR009 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR008 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR007 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR006 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR005 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR004 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR003 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR002 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR001 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	var _GR000 = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _Plat);
	
	this.game.add.tileSprite(1216, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(1152, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(1088, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(1024, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(960, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(896, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(832, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(768, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(704, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(640, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(576, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(512, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(448, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(384, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(320, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(256, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(192, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(128, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(64, 704, 64, 64, 'Ground', 1, _GR000);
	
	this.game.add.tileSprite(0, 704, 64, 64, 'Ground', 0, _GR000);
	
	var _endScreen = this.game.add.group(_prefabRoot_Scene1);
	
	var _startScreen = this.game.add.group(_prefabRoot_Scene1);
	
	var _theDress = this.game.add.physicsGroup(Phaser.Physics.ARCADE, _prefabRoot_Scene1);
	
	// public fields
	
	this.fCollisionLayer = _CollisionLayer;
	this.fWater = _Water;
	this.fW006 = _W006;
	this.fW005 = _W005;
	this.fW004 = _W004;
	this.fW003 = _W003;
	this.fW002 = _W002;
	this.fW001 = _W001;
	this.fHazards = _Hazards;
	this.fFIREWALL = _FIREWALL;
	this.fH010 = _H010;
	this.fH00F = _H00F;
	this.fH00E = _H00E;
	this.fH00D = _H00D;
	this.fH00C = _H00C;
	this.fH00B = _H00B;
	this.fH00A = _H00A;
	this.fH009 = _H009;
	this.fH008 = _H008;
	this.fH007 = _H007;
	this.fH006 = _H006;
	this.fH005 = _H005;
	this.fH004 = _H004;
	this.fH003 = _H003;
	this.fH002 = _H002;
	this.fH001 = _H001;
	this.fH000 = _H000;
	this.fGroundBase = _GroundBase;
	this.fArrows = _Arrows;
	this.fArrow = _arrow;
	this.fPlayer = _player;
	this.fRomans = _Romans;
	this.fPlat = _Plat;
	this.fST004 = _ST004;
	this.fST003 = _ST003;
	this.fST002 = _ST002;
	this.fST001 = _ST001;
	this.fST000 = _ST000;
	this.fPL024 = _PL024;
	this.fPL023 = _PL023;
	this.fPL022 = _PL022;
	this.fPL021 = _PL021;
	this.fPL020 = _PL020;
	this.fPL01F = _PL01F;
	this.fPL01E = _PL01E;
	this.fPL01D = _PL01D;
	this.fPL01C = _PL01C;
	this.fPL01B = _PL01B;
	this.fPL01A = _PL01A;
	this.fPL019 = _PL019;
	this.fPL018 = _PL018;
	this.fPL017 = _PL017;
	this.fPL016 = _PL016;
	this.fPL015 = _PL015;
	this.fPL014 = _PL014;
	this.fPL013 = _PL013;
	this.fPL012 = _PL012;
	this.fPL011 = _PL011;
	this.fPL010 = _PL010;
	this.fPL00F = _PL00F;
	this.fPL00E = _PL00E;
	this.fPL00D = _PL00D;
	this.fPL00C = _PL00C;
	this.fPL00B = _PL00B;
	this.fPL00A = _PL00A;
	this.fPL009 = _PL009;
	this.fPL008 = _PL008;
	this.fPL007 = _PL007;
	this.fPL006 = _PL006;
	this.fPL005 = _PL005;
	this.fPL004 = _PL004;
	this.fPL003 = _PL003;
	this.fPL002 = _PL002;
	this.fPL001 = _PL001;
	this.fPL000 = _PL000;
	this.fOB016 = _OB016;
	this.fOB015 = _OB015;
	this.fOB014 = _OB014;
	this.fOB013 = _OB013;
	this.fOB012 = _OB012;
	this.fOB011 = _OB011;
	this.fOB010 = _OB010;
	this.fOB00F = _OB00F;
	this.fOB00E = _OB00E;
	this.fOB00D = _OB00D;
	this.fOB00C = _OB00C;
	this.fOB00B = _OB00B;
	this.fOB00A = _OB00A;
	this.fOB009 = _OB009;
	this.fOB008 = _OB008;
	this.fOB007 = _OB007;
	this.fOB006 = _OB006;
	this.fOB005 = _OB005;
	this.fOB004 = _OB004;
	this.fOB003 = _OB003;
	this.fOB002 = _OB002;
	this.fOB001 = _OB001;
	this.fOB000 = _OB000;
	this.fGR00A = _GR00A;
	this.fGR009 = _GR009;
	this.fGR008 = _GR008;
	this.fGR007 = _GR007;
	this.fGR006 = _GR006;
	this.fGR005 = _GR005;
	this.fGR004 = _GR004;
	this.fGR003 = _GR003;
	this.fGR002 = _GR002;
	this.fGR001 = _GR001;
	this.fGR000 = _GR000;
	this.fEndScreen = _endScreen;
	this.fStartScreen = _startScreen;
	this.fTheDress = _theDress;
	
}

/** @type Phaser.Group */
var Scene3_proto = Object.create(Phaser.Group.prototype);
Scene3.prototype = Scene3_proto;
Scene3.prototype.constructor = Scene3;

/* --- end generated code --- */
// -- user code here --
